export const UPDATE_EMAIL = "UPDATE_EMAIL";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const UPDATE_USERNAME = "UPDATE_USERNAME";

export const UPDATE_EMAIL_COMPLETE = "UPDATE_EMAIL_COMPLETE";

export const UPDATE_USERNAME_COMPLETE = "UPDATE_USERNAME_COMPLETE";

export const UPDATE_PASSWORD_COMPLETE = "UPDATE_PASSWORD_COMPLETE";

export const UPDATE_ALL_COMPLETE = "UPDATE_ALL_COMPLETE";

export const UPDATE_SHOW_MODAL = "UPDATE_SHOW_MODAL";
